config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root to: 'restaurants#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
resources :restaurants
resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  scope :by_new, ->{ order(updated_at: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true
  validates :first_name, presence: true
  scope :by_id, ->{ order(id: :asc) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @restaurants = Restaurant.all.by_new
    @users = User.all.by_id
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:edit, :show, :update, :destory]

  def index
    @restaurants = Restaurant.all.by_new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurants_path
    else
      render "new"
    end
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit
  end

  def show
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to restaurant_path(@restaurant)
    else
      render "edit"
    end
  end

  def destroy
      @restaurant.destroy
      redirect_to restaurants_path

  end




  private
  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params[:restaurant].permit(:name, :address)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :show, :update, :destory]

  def index
    @users = User.all.by_id
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path
    else
      render "new"
    end
  end

  def new
    @user = User.new
  end

  def edit
  end

  def show
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render "edit"
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params[:user].permit(:first_name, :last_name, :email, :tel)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.haml
-@restaurants.each do |restaurant|
  %hr
  ="名前 :"
  =link_to restaurant.name, restaurant_path(restaurant)
  %br
  ="アドレス :"
  =restaurant.address
  %br
  ="制作日 :"
  =restaurant.created_at
  %br
  ="更新日 :"
  =restaurant.updated_at

%hr
=link_to "新規レストラン登録", new_restaurant_path

%hr
%br

-@users.each do |user|
  %hr
  =" name :"
  =link_to "#{user.first_name} #{user.last_name.upcase}", user_path(user)
  %br
  =" email :"
  =user.email
  %br
  =" tel :"
  =user.tel
  %br
  =link_to "edit", edit_user_path(user)
  =link_to "delete", user_path(user), method: :delete, data: {confirm: "削除しますか？"}

%hr
=link_to "new sign up", new_user_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title RestaurantsGuide
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/restaurants/_form.html.haml
=bootstrap_form_with model: @restaurant, local: true do |f|
  =f.text_field :name
  =f.text_field :address
  =f.submit class: "btn btn-info"

%br
=link_to "レストラン一覧に戻る", restaurants_path

app/views/restaurants/edit.html.haml
= "レストラン編集"
= render 'form'

app/views/restaurants/index.html.haml
-@restaurants.each do |restaurant|
  %hr
  ="名前 :"
  =link_to restaurant.name, restaurant_path(restaurant)
  %br
  ="アドレス :"
  =restaurant.address
  %br
  ="制作日 :"
  =restaurant.created_at
  %br
  ="更新日 :"
  =restaurant.updated_at

%hr
=link_to "新規レストラン登録", new_restaurant_path

app/views/restaurants/new.html.haml
= "新規レストラン登録"
= render 'form'

app/views/restaurants/show.html.haml
=@restaurant.name
%br
=@restaurant.address
%br
%hr
=link_to "レストラン一覧", restaurants_path

%br
=link_to "編集", edit_restaurant_path(@restaurant.id)

%br
=link_to "削除", restaurant_path(@restaurant), method: :delete, data: {confirm: "削除しますか？"}

app/views/users/_form.html.haml
=bootstrap_form_with model: @user, local: true do |f|
  =f.text_field :first_name
  =f.text_field :last_name
  =f.text_field :email
  =f.text_field :tel
  =f.submit class: "btn btn-info"

%br
=link_to "back to the list", users_path

app/views/users/edit.html.haml
= "edit"
= render 'form'

app/views/users/index.html.haml
-@users.each do |user|
  %hr
  =" name :"
  =link_to "#{user.first_name} #{user.last_name.upcase}", user_path(user)
  %br
  =" email :"
  =user.email
  %br
  =" tel :"
  =user.tel
  %br
  =link_to "edit", edit_user_path(user)
  =link_to "delete", user_path(user), method: :delete, data: {confirm: "削除しますか？"}

%hr
=link_to "new sign up", new_user_path

app/views/users/new.html.haml
= "Registrarion"
%br
= render 'form'

app/views/users/show.html.haml
%hr
=@user.first_name
=@user.last_name
%br
=@user.email
%br
=@user.tel
%br
%hr
=link_to "Edit", edit_user_path(@user)
%br
=link_to "Back to the list", users_path